/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Command = {
  name: string;
  title: string;
  mode: "list" | "detail" | "form" | "silent";
  arguments?: Argument[];
};

export interface Manifest {
  title: string;
  description?: string;
  share_target?: {
    command: string;
    params: {
      title?: string;
      text?: string;
      url?: string;
    };
  };
  entrypoint?: string;
  commands: Command[];
}
export interface Argument {
  name: string;
  type: "string" | "boolean";
  optional?: boolean;
}
