/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Command = Copy | Open | Run | Reload | Pop | Exit | Pass;

export interface Copy {
  /**
   * The type of the action.
   */
  type: "copy";
  /**
   * Whether to exit the app after copying.
   */
  exit?: boolean;
  /**
   * The text to copy.
   */
  text: string;
}
export interface Open {
  /**
   * The type of the action.
   */
  type: "open";
  /**
   * Whether to exit the app after opening.
   */
  exit?: boolean;
  /**
   * The target to open.
   */
  target: string;
  app?: Application | Application[];
}
export interface Application {
  platform?: "windows" | "mac" | "linux";
  name: string;
}
export interface Run {
  /**
   * The type of the action.
   */
  type: "run";
  /**
   * The name of the command to run.
   */
  command: string;
  /**
   * The parameters to pass to the command.
   */
  params?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` ".+".
     */
    [k: string]: unknown;
  };
}
export interface Reload {
  type: "reload";
  /**
   * The parameters to pass to the command.
   */
  params?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` ".+".
     */
    [k: string]: unknown;
  };
}
export interface Pop {
  type: "pop";
  /**
   * Whether to reload the page after popping.
   */
  reload?: boolean;
}
export interface Exit {
  type: "exit";
}
export interface Pass {
  type: "pass";
}
