/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Command = {
  name: string;
  title: string;
  mode: "filter" | "generator" | "detail" | "form" | "silent";
  params?: Param[];
};

export interface Manifest {
  title: string;
  homepage?: string;
  description?: string;
  commands: Command[];
}
export interface Param {
  name: string;
  type: "string" | "boolean";
  optional?: boolean;
}
