/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Manifest {
  title: string;
  homepage?: string;
  description?: string;
  commands: Command[];
}
export interface Command {
  mode: "page" | "action" | "silent";
  title: string;
  name: string;
  params?: {
    name?: string;
    type: "string" | "boolean";
    description?: string;
    optional?: boolean;
  }[];
  prefs?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` ".+".
     */
    [k: string]: {
      name?: string;
      type: "string" | "boolean";
      optional?: boolean;
    };
  };
}
