/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Manifest {
  title: string;
  items: Item[];
  homepage?: string;
  description?: string;
  commands: {
    [k: string]: Command;
  };
}
export interface Item {
  command: string;
  title?: string;
  params?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` ".+".
     */
    [k: string]: string | boolean;
  };
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` ".+".
 */
export interface Command {
  mode: "page" | "action" | "silent";
  title: string;
  params?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` ".+".
     */
    [k: string]: {
      name?: string;
      type: "string" | "boolean";
      optional?: boolean;
    };
  };
  prefs?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` ".+".
     */
    [k: string]: {
      name?: string;
      type: "string" | "boolean";
      optional?: boolean;
    };
  };
}
