/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Page = List | Detail;
export type Command =
  | {
      /**
       * The type of the action.
       */
      type: "copy";
      /**
       * Whether to exit the app after copying.
       */
      exit?: boolean;
      /**
       * The text to copy.
       */
      text: string;
    }
  | {
      /**
       * The type of the action.
       */
      type: "open";
      /**
       * Whether to exit the app after opening.
       */
      exit?: boolean;
      /**
       * The url to open.
       */
      url: string;
    }
  | {
      /**
       * The type of the action.
       */
      type: "run";
      /**
       * The name of the command to run.
       */
      command?: string;
      /**
       * The origin of the command to run.
       */
      origin: string;
      /**
       * The parameters to pass to the command.
       */
      params?: {
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` ".+".
         */
        [k: string]: boolean | number | Input;
      };
    }
  | {
      type: "reload";
      /**
       * The parameters to pass to the command.
       */
      params?: {
        [k: string]: unknown;
      };
    };
export type Input =
  | {
      /**
       * The title of the input.
       */
      title: string;
      /**
       * The type of the input.
       */
      type: "textfield";
      /**
       * The placeholder of the input.
       */
      placeholder?: string;
      /**
       * The default value of the input.
       */
      default?: string;
      /**
       * Whether the input should be secure.
       */
      secure?: boolean;
    }
  | {
      /**
       * The title of the input.
       */
      title: string;
      /**
       * The type of the input.
       */
      type: "checkbox";
      /**
       * The default value of the input.
       */
      default?: boolean;
      /**
       * The label of the input.
       */
      label?: string;
    }
  | {
      /**
       * The title of the input.
       */
      title: string;
      /**
       * The type of the input.
       */
      type: "textarea";
      /**
       * The placeholder of the input.
       */
      placeholder?: string;
      /**
       * The default value of the input.
       */
      default?: string;
    }
  | {
      /**
       * The title of the input.
       */
      title: string;
      /**
       * The type of the input.
       */
      type: "dropdown";
      /**
       * The items of the input.
       */
      items: {
        /**
         * The title of the item.
         */
        title: string;
        /**
         * The value of the item.
         */
        value: string;
      }[];
      /**
       * The default value of the input.
       */
      default?: string;
    };

export interface List {
  /**
   * The type of the page.
   */
  type: "list";
  emptyView?: {
    /**
     * The text to show when the list is empty.
     */
    text: string;
    /**
     * The actions to show when the list is empty.
     */
    actions?: Action[];
  };
  /**
   * The items in the list.
   */
  items: Listitem[];
}
export interface Action {
  /**
   * The title of the action.
   */
  title: string;
  /**
   * The key used as a shortcut.
   */
  key?: string;
  onAction: Command;
}
export interface Listitem {
  /**
   * The title of the item.
   */
  title: string;
  /**
   * The id of the item.
   */
  id?: string;
  /**
   * The subtitle of the item.
   */
  subtitle?: string;
  /**
   * The accessories to show on the right side of the item.
   */
  accessories?: string[];
  /**
   * The actions attached to the item.
   */
  actions?: Action[];
}
/**
 * A detail view displaying a preview and actions.
 */
export interface Detail {
  /**
   * The type of the page.
   */
  type: "detail";
  language?: string;
  /**
   * The text to show in the detail view.
   */
  text: string;
  /**
   * The actions attached to the detail view.
   */
  actions?: Action[];
}
