/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Page = List | Detail | Form;
export type Action =
  | {
      /**
       * The type of the action.
       */
      type: "copy";
      /**
       * The title of the action.
       */
      title?: string;
      /**
       * Whether to exit the app after copying.
       */
      exit?: boolean;
      /**
       * The text to copy.
       */
      text: string;
      /**
       * The key used as a shortcut.
       */
      key?: string;
    }
  | {
      /**
       * The type of the action.
       */
      type: "open";
      /**
       * Whether to exit the app after opening.
       */
      exit?: boolean;
      /**
       * The title of the action.
       */
      title?: string;
      /**
       * The key used as a shortcut.
       */
      key?: string;
      /**
       * The url to open.
       */
      url: string;
    }
  | {
      /**
       * The type of the action.
       */
      type: "run";
      /**
       * The title of the action.
       */
      title?: string;
      /**
       * Whether to exit the app after running.
       */
      exit?: boolean;
      /**
       * The key used as a shortcut.
       */
      key?: string;
      command: string;
      params?: Params;
    };

export interface List {
  /**
   * The title of the page.
   */
  title?: string;
  emptyView?: {
    /**
     * The text to show when the list is empty.
     */
    text: string;
    /**
     * The actions to show when the list is empty.
     */
    actions?: Action[];
  };
  /**
   * The items in the list.
   */
  items: Listitem[];
}
export interface Params {
  /**
   * The text to share.
   */
  text?: string;
  /**
   * The url to share.
   */
  url?: string;
  /**
   * The title to share.
   */
  title?: string;
}
export interface Listitem {
  /**
   * The title of the item.
   */
  title: string;
  /**
   * The id of the item.
   */
  id?: string;
  /**
   * The subtitle of the item.
   */
  subtitle?: string;
  /**
   * The accessories to show on the right side of the item.
   */
  accessories?: string[];
  /**
   * The actions attached to the item.
   */
  actions?: Action[];
}
/**
 * A detail view displaying a preview and actions.
 */
export interface Detail {
  /**
   * The title of the page.
   */
  title?: string;
  language?: string;
  /**
   * The text to show in the detail view.
   */
  text: string;
  /**
   * The actions attached to the detail view.
   */
  actions?: Action[];
}
export interface Form {
  /**
   * The title of the page.
   */
  title?: string;
  /**
   * The command to run when the form is submitted.
   */
  command: string;
  params?: Params;
}
