#!/usr/bin/env bash

set -eo pipefail

sunbeam query --null-input '{
    type: "detail",
    title: "Hello, Sunbeam!",
    preview: {text: "Hello, Sunbeam!"},
    actions: [
        {
            type: "copy",
            text: "Hello, sunbeam!",
        }
    ]
}'
