#!/usr/bin/env bash

set -eo pipefail

# Usage: sunbeam run ./sunbeam-extension

sunbeam query --null-input '{
    type: "detail",
    title: "Hello, world!",
    preview: "Hello, world!",
    actions: [
        {
            type: "copy",
            text: "Hello, world!",
        }
    ]
}'
