#!/usr/bin/env bash

# @sunbeam.schemaVersion 1
# @sunbeam.title File Filter
# @sunbeam.mode view

set -euo pipefail

# shellcheck disable=SC2016
find . | sunbeam query -R --arg "pwd=$PWD" '{
    title: .,
    accessories: [$pwd],
    actions: [
        {
            type: "paste",
            title: "Paste",
            text: .
        },
        {
            type: "open",
            title: "Open",
            target: .
        },
        {
            type: "copy",
            title: "Copy Relative Path",
            text: .
        }
    ]
}' | sunbeam list --json --title "Filter Files"
